demo :
	rm -f ../logs/*.cflog
	sh build/run "demo_prv" true

ultrasonic_sensor:
	rm -f ../logs/*.cflog
	sh build/run "ultrasonic_sensor" true

temperature_sensor:
	rm -f ../logs/*.cflog
	sh build/run "temperature_sensor" true

syringe_pump:
	rm -f ../logs/*.cflog
	sh build/run "syringe_pump" true

clean :
	rm -rf simv *.mem pmem.inc stimulus.v tmp-build
